In [5]:
from sklearn.datasets import load_bostan

ImportError: cannot import name 'load_bostan' from 'sklearn.datasets' (C:\Users\Pratik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\__init__.py)

In [3]:
# Load boston dataset
boston = fetch_openml(name='boston',version=1)

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [4]:
boston

NameError: name 'boston' is not defined

In [ ]:
boston.data.shape

In [125]:
boston.data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   CRIM     506 non-null    float64 
 1   ZN       506 non-null    float64 
 2   INDUS    506 non-null    float64 
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64 
 5   RM       506 non-null    float64 
 6   AGE      506 non-null    float64 
 7   DIS      506 non-null    float64 
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64 
 10  PTRATIO  506 non-null    float64 
 11  B        506 non-null    float64 
 12  LSTAT    506 non-null    float64 
dtypes: category(2), float64(11)
memory usage: 45.1 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   CRIM     506 non-null    float64 
 1   ZN       506 non-null    flo

### Import Required Libraries

In [126]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [127]:
# create dataframe
boston.data

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0  \
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0  \
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0  \
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [128]:
boston.feature_names # This give columns name

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

In [129]:
df_x = pd.DataFrame(boston.data,columns=boston.feature_names)

In [130]:
df_y = pd.DataFrame(boston.target)

In [131]:
df_x

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0  \
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0  \
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0  \
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [132]:
df_y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [133]:
df_x.describe()

CRIM          ZN       INDUS         NOX          RM         AGE   
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000  \
mean     3.613524   11.363636   11.136779    0.554695    6.284634   68.574901   
std      8.601545   23.322453    6.860353    0.115878    0.702617   28.148861   
min      0.006320    0.000000    0.460000    0.385000    3.561000    2.900000   
25%      0.082045    0.000000    5.190000    0.449000    5.885500   45.025000   
50%      0.256510    0.000000    9.690000    0.538000    6.208500   77.500000   
75%      3.677083   12.500000   18.100000    0.624000    6.623500   94.075000   
max     88.976200  100.000000   27.740000    0.871000    8.780000  100.000000   

              DIS         TAX     PTRATIO           B       LSTAT  
count  506.000000  506.000000  506.000000  506.000000  506.000000  
mean     3.795043  408.237154   18.455534  356.674032   12.653063  
std      2.105710  168.537116    2.164946   91.294864    7.141062  
min      1.129600  187.000000   12.600000    0.320000    1.730000  
25%      2.100175  279.000000   17.400000  375.377500    6.950000  
50%      3.207450  330.000000   19.050000  391.440000   11.360000  
75%      5.188425  666.000000   20.200000  396.225000   16.955000  
max     12.126500  711.000000   22.000000  396.900000   37.970000

CRIM          ZN       INDUS         NOX          RM         AGE   
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000  \
mean     3.613524   11.363636   11.136779    0.554695    6.284634   68.574901   
std      8.601545   23.322453    6.860353    0.115878    0.702617   28.148861   
min      0.006320    0.000000    0.460000    0.385000    3.561000    2.900000   
25%      0.082045    0.000000    5.190000    0.449000    5.885500   45.025000   
50%      0.256510    0.000000    9.690000    0.538000    6.208500   77.500000   
75%      3.677083   12.500000   18.100000    0.624000    6.623500   94.075000   
max     88.976200  100.000000   27.740000    0.871000    8.780000  100.000000   

              DIS         TAX     PTRATIO           B       LSTAT  
count  506.000000  506.000000  506.000000  506.000000  506.000000  
mean     3.795043  408.237154   18.455534  356.674032   12.653063  
std      2.105710  168.537116    2.164946   91.294864    7.141062  
min      1.129600  187.000000   12.600000    0.320000    1.730000  
25%      2.100175  279.000000   17.400000  375.377500    6.950000  
50%      3.207450  330.000000   19.050000  391.440000   11.360000  
75%      5.188425  666.000000   20.200000  396.225000   16.955000  
max     12.126500  711.000000   22.000000  396.900000   37.970000

CRIM          ZN       INDUS         NOX          RM         AGE   
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000  \
mean     3.613524   11.363636   11.136779    0.554695    6.284634   68.574901   
std      8.601545   23.322453    6.860353    0.115878    0.702617   28.148861   
min      0.006320    0.000000    0.460000    0.385000    3.561000    2.900000   
25%      0.082045    0.000000    5.190000    0.449000    5.885500   45.025000   
50%      0.256510    0.000000    9.690000    0.538000    6.208500   77.500000   
75%      3.677083   12.500000   18.100000    0.624000    6.623500   94.075000   
max     88.976200  100.000000   27.740000    0.871000    8.780000  100.000000   

              DIS         TAX     PTRATIO           B       LSTAT  
count  506.000000  506.000000  506.000000  506.000000  506.000000  
mean     3.795043  408.237154   18.455534  356.674032   12.653063  
std      2.105710  168.537116    2.164946   91.294864    7.141062  
min      1.129600  187.000000   12.600000    0.320000    1.730000  
25%      2.100175  279.000000   17.400000  375.377500    6.950000  
50%      3.207450  330.000000   19.050000  391.440000   11.360000  
75%      5.188425  666.000000   20.200000  396.225000   16.955000  
max     12.126500  711.000000   22.000000  396.900000   37.970000

In [134]:
df_y.describe()

MEDV
count  506.000000
mean    22.532806
std      9.197104
min      5.000000
25%     17.025000
50%     21.200000
75%     25.000000
max     50.000000

MEDV
count  506.000000
mean    22.532806
std      9.197104
min      5.000000
25%     17.025000
50%     21.200000
75%     25.000000
max     50.000000

MEDV
count  506.000000
mean    22.532806
std      9.197104
min      5.000000
25%     17.025000
50%     21.200000
75%     25.000000
max     50.000000

In [135]:
df_x.shape

(506, 13)

(506, 13)

(506, 13)

In [136]:
df_x.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

### Initializing the linear regerssion model

In [137]:
reg = linear_model.LinearRegression()

In [138]:
# splitting data into 70% traning and 30% testing
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size=0.3,random_state=43)

In [139]:
# Tain the model
reg.fit(x_train,y_train)

LinearRegression()

LinearRegression()

LinearRegression()

In [140]:
reg.coef_

array([[-3.14806846e-02,  4.35491340e-02,  3.72218331e-02,
         2.59144276e+00, -1.76489873e+01,  3.78370328e+00,
         2.20848708e-02, -1.24099405e+00,  3.45873260e-01,
        -1.42131333e-02, -1.00537656e+00,  1.13001767e-02,
        -6.47916500e-01]])

array([[-3.14806846e-02,  4.35491340e-02,  3.72218331e-02,
         2.59144276e+00, -1.76489873e+01,  3.78370328e+00,
         2.20848708e-02, -1.24099405e+00,  3.45873260e-01,
        -1.42131333e-02, -1.00537656e+00,  1.13001767e-02,
        -6.47916500e-01]])

array([[-3.14806846e-02,  4.35491340e-02,  3.72218331e-02,
         2.59144276e+00, -1.76489873e+01,  3.78370328e+00,
         2.20848708e-02, -1.24099405e+00,  3.45873260e-01,
        -1.42131333e-02, -1.00537656e+00,  1.13001767e-02,
        -6.47916500e-01]])

In [141]:
x_test

CRIM     ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
360  4.54192    0.0  18.10    0  0.770  6.398  88.0  2.5182  24  666.0  \
391  5.29305    0.0  18.10    0  0.700  6.051  82.5  2.1678  24  666.0   
247  0.19657   22.0   5.86    0  0.431  6.226  79.2  8.0555   7  330.0   
57   0.01432  100.0   1.32    0  0.411  6.816  40.5  8.3248   5  256.0   
244  0.20608   22.0   5.86    0  0.431  5.593  76.5  7.9549   7  330.0   
..       ...    ...    ...  ...    ...    ...   ...     ...  ..    ...   
0    0.00632   18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0   
321  0.18159    0.0   7.38    0  0.493  6.376  54.3  4.5404   5  287.0   
336  0.03427    0.0   5.19    0  0.515  5.869  46.3  5.2311   5  224.0   
210  0.17446    0.0  10.59    1  0.489  5.960  92.1  3.8771   4  277.0   
231  0.46296    0.0   6.20    0  0.504  7.412  76.9  3.6715   8  307.0   

     PTRATIO       B  LSTAT  
360     20.2  374.56   7.79  
391     20.2  378.38  18.76  
247     19.1  376.14  10.15  
57      15.1  392.90   3.95  
244     19.1  372.49  12.50  
..       ...     ...    ...  
0       15.3  396.90   4.98  
321     19.6  396.90   6.87  
336     20.2  396.90   9.80  
210     18.6  393.25  17.27  
231     17.4  376.14   5.25  

[152 rows x 13 columns]

CRIM     ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
360  4.54192    0.0  18.10    0  0.770  6.398  88.0  2.5182  24  666.0  \
391  5.29305    0.0  18.10    0  0.700  6.051  82.5  2.1678  24  666.0   
247  0.19657   22.0   5.86    0  0.431  6.226  79.2  8.0555   7  330.0   
57   0.01432  100.0   1.32    0  0.411  6.816  40.5  8.3248   5  256.0   
244  0.20608   22.0   5.86    0  0.431  5.593  76.5  7.9549   7  330.0   
..       ...    ...    ...  ...    ...    ...   ...     ...  ..    ...   
0    0.00632   18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0   
321  0.18159    0.0   7.38    0  0.493  6.376  54.3  4.5404   5  287.0   
336  0.03427    0.0   5.19    0  0.515  5.869  46.3  5.2311   5  224.0   
210  0.17446    0.0  10.59    1  0.489  5.960  92.1  3.8771   4  277.0   
231  0.46296    0.0   6.20    0  0.504  7.412  76.9  3.6715   8  307.0   

     PTRATIO       B  LSTAT  
360     20.2  374.56   7.79  
391     20.2  378.38  18.76  
247     19.1  376.14  10.15  
57      15.1  392.90   3.95  
244     19.1  372.49  12.50  
..       ...     ...    ...  
0       15.3  396.90   4.98  
321     19.6  396.90   6.87  
336     20.2  396.90   9.80  
210     18.6  393.25  17.27  
231     17.4  376.14   5.25  

[152 rows x 13 columns]

CRIM     ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX   
360  4.54192    0.0  18.10    0  0.770  6.398  88.0  2.5182  24  666.0  \
391  5.29305    0.0  18.10    0  0.700  6.051  82.5  2.1678  24  666.0   
247  0.19657   22.0   5.86    0  0.431  6.226  79.2  8.0555   7  330.0   
57   0.01432  100.0   1.32    0  0.411  6.816  40.5  8.3248   5  256.0   
244  0.20608   22.0   5.86    0  0.431  5.593  76.5  7.9549   7  330.0   
..       ...    ...    ...  ...    ...    ...   ...     ...  ..    ...   
0    0.00632   18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0   
321  0.18159    0.0   7.38    0  0.493  6.376  54.3  4.5404   5  287.0   
336  0.03427    0.0   5.19    0  0.515  5.869  46.3  5.2311   5  224.0   
210  0.17446    0.0  10.59    1  0.489  5.960  92.1  3.8771   4  277.0   
231  0.46296    0.0   6.20    0  0.504  7.412  76.9  3.6715   8  307.0   

     PTRATIO       B  LSTAT  
360     20.2  374.56   7.79  
391     20.2  378.38  18.76  
247     19.1  376.14  10.15  
57      15.1  392.90   3.95  
244     19.1  372.49  12.50  
..       ...     ...    ...  
0       15.3  396.90   4.98  
321     19.6  396.90   6.87  
336     20.2  396.90   9.80  
210     18.6  393.25  17.27  
231     17.4  376.14   5.25  

[152 rows x 13 columns]

In [142]:
x_test['CHAS'] = x_test['CHAS'].astype('float64')
x_test['RAD'] = x_test['RAD'].astype('float64')

In [143]:
x_test.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

In [144]:
y_pred = reg.predict(x_test)

In [145]:
print(np.mean((y_pred-y_test)**2))

25.40889031475487
25.40889031475487
25.40889031475487


In [146]:
from sklearn.metrics import mean_squared_error

In [147]:
print(mean_squared_error(y_test,y_pred))

25.40889031475487
25.40889031475487
25.40889031475487


In [148]:
y_pred

array([[23.49502283],
       [16.64276102],
       [20.89086257],
       [34.10893059],
       [16.99684444],
       [12.37651684],
       [13.23003113],
       [25.10420394],
       [22.52995858],
       [ 7.35571615],
       [27.9213835 ],
       [26.67641743],
       [16.5561431 ],
       [20.90705209],
       [22.21161678],
       [12.02679628],
       [31.82627493],
       [33.10034681],
       [14.52291086],
       [41.17452207],
       [20.72250171],
       [ 8.22482989],
       [21.00552944],
       [31.66548137],
       [ 6.38626137],
       [25.47222083],
       [20.14001182],
       [19.75581079],
       [19.23289073],
       [ 6.55277632],
       [21.47501184],
       [23.54992827],
       [15.5442664 ],
       [ 8.8745995 ],
       [24.34972669],
       [18.87328807],
       [16.18536356],
       [20.56369472],
       [28.67823077],
       [26.60884989],
       [20.7244171 ],
       [ 5.28560207],
       [25.65967531],
       [17.89886503],
       [38.73954273],
       [18

array([[23.49502283],
       [16.64276102],
       [20.89086257],
       [34.10893059],
       [16.99684444],
       [12.37651684],
       [13.23003113],
       [25.10420394],
       [22.52995858],
       [ 7.35571615],
       [27.9213835 ],
       [26.67641743],
       [16.5561431 ],
       [20.90705209],
       [22.21161678],
       [12.02679628],
       [31.82627493],
       [33.10034681],
       [14.52291086],
       [41.17452207],
       [20.72250171],
       [ 8.22482989],
       [21.00552944],
       [31.66548137],
       [ 6.38626137],
       [25.47222083],
       [20.14001182],
       [19.75581079],
       [19.23289073],
       [ 6.55277632],
       [21.47501184],
       [23.54992827],
       [15.5442664 ],
       [ 8.8745995 ],
       [24.34972669],
       [18.87328807],
       [16.18536356],
       [20.56369472],
       [28.67823077],
       [26.60884989],
       [20.7244171 ],
       [ 5.28560207],
       [25.65967531],
       [17.89886503],
       [38.73954273],
       [18

array([[23.49502283],
       [16.64276102],
       [20.89086257],
       [34.10893059],
       [16.99684444],
       [12.37651684],
       [13.23003113],
       [25.10420394],
       [22.52995858],
       [ 7.35571615],
       [27.9213835 ],
       [26.67641743],
       [16.5561431 ],
       [20.90705209],
       [22.21161678],
       [12.02679628],
       [31.82627493],
       [33.10034681],
       [14.52291086],
       [41.17452207],
       [20.72250171],
       [ 8.22482989],
       [21.00552944],
       [31.66548137],
       [ 6.38626137],
       [25.47222083],
       [20.14001182],
       [19.75581079],
       [19.23289073],
       [ 6.55277632],
       [21.47501184],
       [23.54992827],
       [15.5442664 ],
       [ 8.8745995 ],
       [24.34972669],
       [18.87328807],
       [16.18536356],
       [20.56369472],
       [28.67823077],
       [26.60884989],
       [20.7244171 ],
       [ 5.28560207],
       [25.65967531],
       [17.89886503],
       [38.73954273],
       [18